// Create tab: tools that turn a recording into something NEW — study guide, flashcards, quiz, meeting recap,
// action plan, drafts, Q&A, episode notes — plus Export. (Information extracted from the recording lives in
// Notes.) The list adapts to the recording type.
// Nothing is generated by opening the tab: every tool waits for an explicit "Create" click, and finished
// outputs are stored and reopened for free. Interactive parts (flashcards, quiz) run entirely in the browser.
import { fmtClock, RECORDING_TYPE_LABEL } from '../lib/segments.js';
import { mascotSignal } from '../mascot/bus.js';
import { TOOL_SETTINGS, MAX_INSTRUCTIONS, INSTRUCTIONS_MISSING, normalizeToolSettings, describeSettings, quizQuestionCount } from '../lib/tool-settings.js';
import { newRun, currentItem, answeredCount, correctCount, answer as gradeAnswer, overrideCorrect, advance, summary } from './quiz-engine.js';

const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

// small line icons for the study screens (decorative: every state is also said in words)
const svg = (d) => `<svg class="ic" viewBox="0 0 24 24" aria-hidden="true" focusable="false">${d}</svg>`;
const ICON = {
  check: svg('<path d="M5 12.5 10 17.5 19.5 7"/>'),
  x: svg('<path d="M7 7l10 10M17 7 7 17"/>'),
  close: svg('<path d="M7 7l10 10M17 7 7 17"/>'),
  headphones: svg('<path d="M4 15v-3a8 8 0 0 1 16 0v3"/><rect x="3.5" y="14" width="4.5" height="6.5" rx="1.6"/><rect x="16" y="14" width="4.5" height="6.5" rx="1.6"/>'),
  quote: svg('<path d="M5 6h14M5 11h14M5 16h9"/>'),
  loop: svg('<path d="M4 12a8 8 0 0 1 13.7-5.6L20 8.7M20 4v4.7h-4.7M20 12a8 8 0 0 1-13.7 5.6L4 15.3M4 20v-4.7h4.7"/>'),
  quiz: svg('<path d="M9.2 9.3a2.9 2.9 0 1 1 3.9 2.7c-.7.3-1.1.9-1.1 1.6v.6"/><circle cx="12" cy="17.6" r=".9" fill="currentColor" stroke="none"/><rect x="3.5" y="3.5" width="17" height="17" rx="5"/>'),
};

// ---------- catalog ----------
export const TOOL_INFO = {
  study_guide: { label: 'Study Guide', desc: 'Build a study guide from what was taught: topics, concepts, examples and exam information.', loading: 'Writing your study guide' },
  flashcards: { label: 'Flashcards', desc: 'Make flashcards that test what was actually said.', loading: 'Making flashcards' },
  quiz: { label: 'Practice Quiz', desc: 'Test yourself one question at a time, with the proof from the recording after every answer.', loading: 'Writing quiz questions' },
  meeting_recap: { label: 'Meeting Recap', desc: 'Write a clean recap: overview, decisions, action items, open questions and dates.', loading: 'Writing the meeting recap' },
  action_plan: { label: 'Action Plan', desc: 'Turn the tasks that were stated into a plan grouped by owner.', loading: 'Building the action plan' },
  followup_email: { label: 'Follow-up Email', desc: 'You say what the email should be about; SparkScribe fills in the details from the recording.', loading: 'Drafting the email', draft: true },
  reply_draft: { label: 'Reply Draft', desc: 'You say what the reply should be about; SparkScribe fills in the details from the recording.', loading: 'Drafting a reply', draft: true },
  interview_qa: { label: 'Interview Q&A', desc: 'Turn the conversation into a clean Q&A with verbatim quotes.', loading: 'Organizing questions and answers' },
  episode_notes: { label: 'Episode Notes', desc: 'Write shareable episode notes: summary, chapter outline, takeaways and quotes.', loading: 'Writing episode notes' },
  // created before definitions and exam points moved to Notes; still shown in Export if they exist
  definitions: { label: 'Key Definitions', desc: '', loading: 'Collecting definitions' },
  exam_points: { label: 'Possible Exam Points', desc: '', loading: 'Looking for exam information' },
};

// What each recording type offers in Create. Extracted information (actions, decisions, dates, definitions,
// exam information, quotes…) is in Notes, not here.
const CATALOG = {
  lecture: ['study_guide', 'flashcards', 'quiz'],
  meeting: ['meeting_recap', 'action_plan', 'followup_email'],
  interview: ['interview_qa'],
  podcast: ['episode_notes'],
  general: ['action_plan'],
  voice_message: ['reply_draft'],
};
export const toolsFor = (type) => ({ tools: CATALOG[type] || CATALOG.general });
// Every tool works on any recording; the type only decides which are suggested first. The rest are always
// one click away under "More tools" (a voice note can still get a quiz).
const TOOL_GROUPS = [
  ['Study', ['quiz', 'flashcards', 'study_guide']],
  ['Work', ['meeting_recap', 'action_plan', 'followup_email', 'reply_draft']],
  ['Media', ['interview_qa', 'episode_notes']],
];

// tools whose result depends mostly on what the user wants: they open a short setup dialog first
const SETUP_DIALOG = new Set(['reply_draft', 'followup_email']);

// ---------- text form (Copy / Export) ----------
// Every output becomes simple blocks: { t: 'h' | 'p' | 'li' | 'quote' | 'meta', text, time? }
export function artifactBlocks(kind, c, timeOf) {
  if (!c) return [];
  const B = [];
  const h = (text) => B.push({ t: 'h', text });
  const p = (text) => text && B.push({ t: 'p', text });
  const li = (text, refs) => B.push({ t: 'li', text, time: timeOf(refs) });
  const quote = (text, by, refs) => B.push({ t: 'quote', text: `“${text}”${by ? ` — ${by}` : ''}`, time: timeOf(refs) });
  const section = (title, items, fmt) => { if (items?.length) { h(title); items.forEach(fmt); } };
  const action = (a) => li(`${a.task} — Owner: ${a.owner || 'Not specified'} · Deadline: ${a.deadline || 'Not specified'}${a.evidence ? ` (“${a.evidence}”)` : ''}`, a.refs);
  switch (kind) {
    case 'study_guide':
      section('Overview', [c.overview].filter(Boolean), p);
      section('Major topics', c.topics, (t) => B.push({ t: 'li', text: `${t.title}: ${t.summary}`, time: t.start_ref != null ? timeOf([t.start_ref]) : null }));
      section('Important concepts', c.concepts, (x) => li(`${x.term}: ${x.explanation}`, x.refs));
      section('Definitions', c.definitions, (x) => li(`${x.term}: ${x.definition}`, x.refs));
      section('Examples', c.examples, (x) => li(x.text, x.refs));
      section('Processes and sequences', c.processes, (x) => li(`${x.name}: ${x.steps.map((s, i) => `${i + 1}. ${s}`).join(' ')}`, x.refs));
      section('Important relationships', c.relationships, (x) => li(x.text, x.refs));
      section('What the lecturer emphasised', c.emphasis, (x) => li(`${x.text} (“${x.evidence}”)`, x.refs));
      section('Explicit exam information', c.exam_info, (x) => li(`${x.text} (“${x.evidence}”)`, x.refs));
      section('Worth reviewing', c.review, (x) => li(x.text, x.refs));
      break;
    case 'flashcards':
      (c.cards || []).forEach((k, i) => { h(`Card ${i + 1}`); B.push({ t: 'p', text: `Q: ${k.front}` }); B.push({ t: 'p', text: `A: ${k.back}`, time: timeOf(k.refs) }); });
      break;
    case 'quiz':
      (c.questions || []).forEach((q, i) => {
        h(`Question ${i + 1}`);
        p(q.question);
        (q.options || []).forEach((o, j) => B.push({ t: 'li', text: q.type === 'multiple_choice' ? `${String.fromCharCode(65 + j)}. ${o}` : o }));
        B.push({ t: 'p', text: `Answer: ${q.answer}${q.explanation ? ` — ${q.explanation}` : ''}`, time: timeOf(q.refs) });
      });
      break;
    case 'definitions': section('Key definitions', c.definitions, (x) => li(`${x.term}: ${x.definition}`, x.refs)); break;
    case 'exam_points':
      section('Explicit exam information', c.explicit, (x) => li(`${x.text} (“${x.evidence}”)`, x.refs));
      section('Worth reviewing (not tied to an exam)', c.worth_reviewing, (x) => li(`${x.text}${x.reason ? ` — ${x.reason}` : ''}`, x.refs));
      break;
    case 'meeting_recap':
      section('Meeting overview', [c.overview].filter(Boolean), p);
      section('Participants', c.participants?.length ? [c.participants.map((x) => x.label).join(', ')] : [], p);
      section('Topics discussed', c.topics, (t) => B.push({ t: 'li', text: `${t.title}: ${t.summary}`, time: t.start_ref != null ? timeOf([t.start_ref]) : null }));
      section('Confirmed decisions', c.decisions, (d) => li(`${d.text} (“${d.evidence}”)`, d.refs));
      section('Action items', c.action_items, action);
      section('Open questions', c.open_questions, (x) => li(x.text, x.refs));
      section('Follow-ups', c.follow_ups, (x) => li(x.text, x.refs));
      section('Important dates', c.important_dates, (x) => li(`${x.when}: ${x.what}`, x.refs));
      break;
    case 'action_plan':
      if (!c.tasks?.length) p('No tasks were stated in this recording.');
      for (const [owner, tasks] of groupByOwner(c.tasks || [])) section(owner, tasks, action);
      break;
    case 'followup_email':
      B.push({ t: 'meta', text: 'Draft — review before sending.' });
      p(`Subject: ${c.subject}`);
      B.push({ t: 'pre', text: c.body });
      break;
    case 'reply_draft':
      B.push({ t: 'meta', text: 'Draft reply — review before sending.' });
      B.push({ t: 'pre', text: c.reply });
      break;
    case 'interview_qa':
      if (c.is_interview === false) B.push({ t: 'meta', text: 'This recording is not mainly a question-and-answer exchange.' });
      (c.pairs || []).forEach((x, i) => {
        h(`Q${i + 1}${x.asked_by ? ` (${x.asked_by})` : ''}: ${x.question}`);
        B.push({ t: 'p', text: `${x.answered_by ? `${x.answered_by}: ` : ''}${x.response}`, time: timeOf(x.refs) });
      });
      section('Important quotes', c.quotes, (x) => quote(x.quote, x.speaker, x.refs));
      break;
    case 'episode_notes':
      section('Episode summary', [c.summary].filter(Boolean), p);
      section('Chapter outline', c.outline, (t) => B.push({ t: 'li', text: `${t.title}: ${t.summary}`, time: t.start_ref != null ? timeOf([t.start_ref]) : null }));
      section('Key takeaways', c.takeaways, (x) => li(x.text, x.refs));
      section('Important quotes', c.quotes, (x) => quote(x.quote, x.speaker, x.refs));
      break;
    default: break;
  }
  return B;
}

export function blocksToText(blocks) {
  return blocks.map((b) => {
    const t = b.time != null ? ` [${fmtClock(b.time)}]` : '';
    if (b.t === 'h') return `\n${b.text}\n`;
    if (b.t === 'li') return `- ${b.text}${t}`;
    return `${b.text}${t}`;
  }).join('\n').replace(/^\n+/, '').trim() + '\n';
}

function groupByOwner(tasks) {
  const groups = new Map();
  for (const t of tasks) {
    const k = t.owner || 'Owner not specified';
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(t);
  }
  return [...groups].sort((a, b) => (a[0] === 'Owner not specified') - (b[0] === 'Owner not specified'));
}

// ---------- short-answer checking (lenient, with a manual override in the UI) ----------
const STOP = new Set('a an the of to in on for and or is are was were be by with that this it its as at from'.split(' '));
const words = (s) => String(s || '').toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu, ' ').trim().split(' ').filter((w) => w && !STOP.has(w));
export function shortAnswerCorrect(given, q) {
  const g = words(given);
  if (!g.length) return false;
  return [q.answer, ...(q.accept || [])].some((ans) => {
    const a = words(ans);
    if (!a.length) return false;
    if (a.join(' ') === g.join(' ')) return true;
    const gs = new Set(g);
    return a.filter((w) => gs.has(w)).length / a.length >= 0.75; // most of the expected words are there
  });
}

// ---------- the Create tab ----------
/**
 * @param {object} api  helpers from insights.js:
 *   type(), contentVersion(), artifact(kind, key), busy(kind, key), error(kind, key), generate(kind, settings, force),
 *   remove(artifact), saveProgress(artifact, progress), chips(refs, byId), segById(), loading(label), errorBox(err, act),
 *   artifactsOf(kind), makeDialog(className, html), showTab(name), openExport(preselect), copy(text, label), privacyLine,
 *   canPlay() → the recording's audio is open on this page, duration() → seconds
 */
export function createToolsUI(api) {
  // sel: the settings the user is looking at for each tool (defaults to those of the latest result)
  const ui = { tool: null, sel: {}, deck: new Map(), quiz: new Map(), autoStart: null, focus: null, quizKey: null };
  const keyOf = (kind, settings) => normalizeToolSettings(kind, settings).key;
  const latest = (kind) => api.artifactsOf(kind).filter((a) => a.content || a.status === 'generating')
    .sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)))[0] || null;
  const selOf = (kind) => (ui.sel[kind] ||= { ...(latest(kind)?.settings || normalizeToolSettings(kind, {}).settings) });
  // the result on screen: the one for the chosen settings; for drafts, otherwise the latest draft (drafts
  // saved before Phase 5.6 have keys from older settings, so they are found by recency, not by key)
  function current(kind) {
    const key = keyOf(kind, selOf(kind));
    const a = api.artifact(kind, key);
    if (a || !SETUP_DIALOG.has(kind) || api.busy(kind, key) || api.error(kind, key)) return { key, a };
    const l = latest(kind);
    return l ? { key: l.settingsKey, a: l } : { key, a: null };
  }

  function status(kind) {
    const a = latest(kind) || api.artifact(kind, '');
    if (api.artifactsOf(kind).some((x) => api.busy(kind, x.settingsKey)) || api.busy(kind, keyOf(kind, selOf(kind))) || a?.status === 'generating') return ['busy', 'Creating…'];
    if (a?.status === 'failed' && !a.content) return ['bad', 'Failed'];
    if (a?.content && api.contentVersion() != null && a.sourceVersion < api.contentVersion()) return ['warn', 'Out of date'];
    if (a?.content) {
      if (kind === 'quiz' && a.progress?.last_score != null) return ['ok', `Last score ${a.progress.last_score}/${a.progress.total}`];
      return ['ok', 'Ready'];
    }
    return ['', SETUP_DIALOG.has(kind) ? 'Not created · asks what you want first' : 'Not created'];
  }

  function renderList() {
    const suggested = toolsFor(api.type()).tools;
    const cards = suggested.map((kind) => {
      const info = TOOL_INFO[kind];
      const [cls, label] = status(kind);
      return `<button type="button" class="tool-card" data-tool="${kind}">
        <span class="tool-name">${esc(info.label)}</span>
        <span class="tool-desc">${esc(info.desc)}</span>
        <span class="tool-state ${cls}">${esc(label)}</span>
      </button>`;
    }).join('');
    // the other tools, compact: name + state; grouped so "Quiz" is easy to find on any recording
    const more = TOOL_GROUPS.map(([group, kinds]) => {
      const rest = kinds.filter((k) => !suggested.includes(k));
      if (!rest.length) return '';
      return `<div class="tool-more-group"><span class="tool-more-label">${esc(group)}</span>${rest.map((kind) => {
        const [cls, label] = status(kind);
        const made = cls === 'ok' || cls === 'warn' || cls === 'busy';
        return `<button type="button" class="tool-chip${made ? ' made' : ''}" data-tool="${kind}" title="${esc(TOOL_INFO[kind].desc)}">${esc(TOOL_INFO[kind].label)}${made ? `<span class="tool-chip-state ${cls}">${esc(label)}</span>` : ''}</button>`;
      }).join('')}</div>`;
    }).join('');
    return `<p class="tab-intro">Quizzes, study tools, recaps and drafts made from this recording.</p>
      <div class="panel ins-card">
        <div class="ins-label">Suggested for this ${esc(api.type() === 'general' ? 'recording' : (RECORDING_TYPE_LABEL[api.type()] || 'recording').toLowerCase())}</div>
        <p class="ins-sub">Nothing is created until you choose a tool. Everything you create is saved with the recording.</p>
        <div class="tool-grid">${cards}
          <button type="button" class="tool-card export" data-tool="export">
            <span class="tool-name">Export</span><span class="tool-desc">Download the transcript, summary, notes and anything you created as PDF, Word, Markdown, text or subtitles.</span>
            <span class="tool-state">No AI used</span>
          </button>
        </div>
        <div class="tool-more" aria-label="More tools"><div class="ins-label">More tools</div>${more}</div>
        <button type="button" class="tool-note-link" data-goto="notes">Looking for actions, dates or decisions from the recording? They’re in Notes →</button>
      </div>`;
  }

  // inline choices (flashcards / quiz / study guide)
  function settingsHtml(kind, sel) {
    const spec = TOOL_SETTINGS[kind];
    if (!spec || SETUP_DIALOG.has(kind)) return '';
    return `<div class="tool-settings">${Object.entries(spec).map(([name, sp]) => `<div class="tool-set"><span class="ins-label">${esc(sp.label)}</span><div class="seg-toggle" role="group" aria-label="${esc(sp.label)}">${Object.entries(sp.options).map(([v, l]) => `<button type="button" data-set="${name}" data-val="${v}" class="${sel[name] === v ? 'on' : ''}" aria-pressed="${sel[name] === v}">${esc(l)}</button>`).join('')}</div></div>`).join('')}</div>`;
  }

  function renderTool() {
    const kind = ui.tool;
    const info = TOOL_INFO[kind];
    const sel = selOf(kind);
    const { key, a } = current(kind);
    const busy = api.busy(kind, key) || a?.status === 'generating';
    const err = api.error(kind, key) || (a?.status === 'failed' ? { message: a.error } : null);
    const stale = a?.content && api.contentVersion() != null && a.sourceVersion < api.contentVersion();
    const byId = api.segById();
    const dialogTool = SETUP_DIALOG.has(kind);
    const desc = describeSettings(kind, a?.settings || sel);
    let html = `<div class="panel ins-card tool-view">
      <div class="tool-head"><button type="button" class="btn btn-ghost btn-sm" data-act="tools">← All tools</button><h3>${esc(info.label)}</h3></div>`;
    html += settingsHtml(kind, sel);
    if (dialogTool && a?.content) {
      html += `<div class="tool-setup-sum"><span>${a.settings?.instructions ? `You asked: “${esc(a.settings.instructions)}”` : 'Drafted from the recording only'}</span><button class="btn btn-ghost btn-sm" type="button" data-act="setup">New draft…</button></div>`;
    }
    // drafts are redone through the request box (an old draft may not have a request yet)
    if (stale && !busy) html += `<div class="ins-msg warn"><span>Out of date: the transcript changed after this was created.</span><button class="btn btn-ghost btn-sm" type="button" data-act="${dialogTool ? 'setup' : 'regen'}">Update</button></div>`;
    if (busy) html += api.loading(info.loading);
    if (err && !busy) html += api.errorBox(err, 'regen', a?.content ? "The update didn't work; your previous version is still below." : "This couldn't be created.");
    if (a?.content) {
      if (info.draft) html += `<div class="ins-msg"><span><b>Draft.</b> Facts come from the recording${a.settings?.instructions ? ', plus what you asked for' : ''}. Check it before you send it; SparkScribe never sends anything for you.</span></div>`;
      html += `<div class="tool-body" data-kind="${kind}">${body(kind, a, byId)}</div>`;
      html += `<div class="tool-actions">
        <button class="btn btn-ghost btn-sm" type="button" data-act="copy">Copy</button>
        <button class="btn btn-ghost btn-sm" type="button" data-act="export">Export…</button>
        ${!stale && !busy && !dialogTool ? '<button class="btn btn-ghost btn-sm" type="button" data-act="regen-confirm">Regenerate</button>' : ''}
        <button class="btn btn-ghost btn-sm tool-del" type="button" data-act="delete">Delete ${esc(info.label)}</button>
      </div>`;
    } else if (!busy && !err) {
      const other = !dialogTool && api.artifactsOf(kind).some((x) => x.content);
      html += `<div class="ins-intro-row"><p>${esc(info.desc)}${desc ? ` <span class="ins-sub">(${esc(desc)})</span>` : ''}${other ? ' <span class="ins-sub">You have a version with other settings: switch back to see it.</span>' : ''}</p>
        <button class="btn btn-primary" type="button" data-act="${dialogTool ? 'setup' : 'create'}">${dialogTool ? `${kind === 'reply_draft' ? 'Draft a reply' : 'Draft an email'}…` : `Create ${esc(info.label)}`}</button></div>${api.privacyLine}`;
    }
    return html + '</div>';
  }

  // Reply / email: the user writes what the draft should be about before anything is generated
  function openSetup(kind) {
    const cur = selOf(kind);
    const reply = kind === 'reply_draft';
    const example = reply ? 'e.g. Ask him what timeline he has in mind and confirm that I’ll look into shipping costs.' : 'e.g. Recap what we agreed on and ask Speaker 2 to confirm the launch date.';
    const { dlg, dismiss } = api.makeDialog('setup-dlg', `<form class="dlg-form" autocomplete="off" novalidate>
        <h3>${reply ? 'Draft a reply' : 'Draft a follow-up email'}</h3>
        <label class="dlg-field"><span class="ins-label">What should the ${reply ? 'reply' : 'email'} be about?</span>
          <textarea rows="4" maxlength="${MAX_INSTRUCTIONS}" required placeholder="${esc(example)}">${esc(cur.instructions || '')}</textarea></label>
        <p class="ins-sub">Tell SparkScribe what you want the ${reply ? 'reply' : 'email'} to say or accomplish. Recording facts will be used for context. Anything you write here, like a day or a promise, is included because you asked for it; nothing else is promised.</p>
        <p class="dlg-err" role="alert" hidden></p>
        <div class="confirm-actions"><button class="btn btn-ghost" type="button" data-act="cancel">Cancel</button><button class="btn btn-primary" type="submit">${reply ? 'Generate Reply' : 'Generate Email'}</button></div>
      </form>`);
    const box = dlg.querySelector('textarea');
    const er = dlg.querySelector('.dlg-err');
    box.addEventListener('input', () => { er.hidden = true; });
    dlg.querySelector('[data-act=cancel]').addEventListener('click', dismiss);
    dlg.querySelector('form').addEventListener('submit', (e) => {
      e.preventDefault();
      const instructions = box.value.trim();
      if (!instructions) {
        er.textContent = INSTRUCTIONS_MISSING[kind];
        er.hidden = false;
        box.focus();
        return;
      }
      ui.sel[kind] = { instructions };
      dismiss();
      api.generate(kind, ui.sel[kind], false);
      api.refresh();
    });
    box.focus();
  }

  // ---------- per-tool bodies ----------
  function body(kind, a, byId) {
    const c = a.content;
    const chips = (refs) => api.chips(refs, byId);
    const at = (ref) => { const s = byId.get(ref); return s ? `<button class="cite" type="button" data-seek="${s.start}" data-ref="${s.id}">${fmtClock(s.start)}</button>` : ''; };
    const list = (title, items, fmt, note) => (items?.length ? `<section class="tool-sec"><h4>${esc(title)}</h4>${note ? `<p class="ins-sub">${esc(note)}</p>` : ''}<ul class="ins-points">${items.map(fmt).join('')}</ul></section>` : '');
    const ev = (e) => (e ? `<blockquote class="evidence">“${esc(e)}”</blockquote>` : '');
    const action = (x) => `<li class="ins-item action"><div class="act-task">${esc(x.task)}</div><dl class="act-meta"><div><dt>Owner</dt><dd class="${x.owner ? '' : 'ns'}">${esc(x.owner || 'Not specified')}</dd></div><div><dt>Deadline</dt><dd class="${x.deadline ? '' : 'ns'}">${esc(x.deadline || 'Not specified')}</dd></div></dl>${ev(x.evidence)}<div class="act-cites">${chips(x.refs)}</div></li>`;
    const topics = (title, items) => (items?.length ? `<section class="tool-sec"><h4>${esc(title)}</h4><ol class="chapters">${items.map((t) => {
      const s = t.start_ref != null ? byId.get(t.start_ref) : null;
      return `<li>${s ? `<button type="button" class="chapter" data-seek="${s.start}" data-ref="${s.id}"><span class="ch-time">${fmtClock(s.start)}</span>` : '<div class="chapter static"><span class="ch-time">—</span>'}<span class="ch-body"><span class="ch-title">${esc(t.title)}</span><span class="ch-sum">${esc(t.summary)}</span></span>${s ? '</button>' : '</div>'}</li>`;
    }).join('')}</ol></section>` : '');
    const quotes = (items) => list('Important quotes', items, (x) => `<li class="ins-item quote"><blockquote>“${esc(x.quote)}”</blockquote><span class="q-by">${esc(x.speaker)}</span>${chips(x.refs)}</li>`, 'Word for word from the transcript.');
    switch (kind) {
      case 'study_guide':
        return `${c.overview ? `<p class="tool-lead">${esc(c.overview)}</p>` : ''}
          ${topics('Major topics', c.topics)}
          ${list('Important concepts', c.concepts, (x) => `<li><span><b>${esc(x.term)}</b> — ${esc(x.explanation)}</span></li>`)}
          ${list('Definitions', c.definitions, (x) => `<li><span><b>${esc(x.term)}</b>: ${esc(x.definition)}</span>${chips(x.refs)}</li>`, 'As defined in the lecture.')}
          ${list('Examples', c.examples, (x) => `<li><span>${esc(x.text)}</span></li>`)}
          ${list('Processes & sequences', c.processes, (x) => `<li><span><b>${esc(x.name)}</b>${chips(x.refs)}</span><ol class="steps">${x.steps.map((s) => `<li>${esc(s)}</li>`).join('')}</ol></li>`)}
          ${list('Important relationships', c.relationships, (x) => `<li><span>${esc(x.text)}</span></li>`)}
          ${list('What the lecturer emphasised', c.emphasis, (x) => `<li><span>${esc(x.text)}</span>${ev(x.evidence)}${chips(x.refs)}</li>`)}
          ${list('Explicit exam information', c.exam_info, (x) => `<li><span>${esc(x.text)}</span>${ev(x.evidence)}${chips(x.refs)}</li>`, 'Only where the lecturer mentioned an exam, test, quiz or assignment.')}
          ${list('Worth reviewing', c.review, (x) => `<li><span>${esc(x.text)}</span></li>`, 'Seems important — not tied to an exam in the recording.')}`;
      case 'definitions':
        return c.definitions?.length ? list('Key definitions', c.definitions, (x) => `<li><span><b>${esc(x.term)}</b>: ${esc(x.definition)}</span>${ev(x.evidence)}${chips(x.refs)}</li>`) : '<p class="ins-none">No terms were explicitly defined in this recording.</p>';
      case 'exam_points':
        return (list('Explicit exam information', c.explicit, (x) => `<li><span>${esc(x.text)}</span>${ev(x.evidence)}${chips(x.refs)}</li>`, 'The lecturer connected these to an exam, test, quiz or assignment.') || '<section class="tool-sec"><h4>Explicit exam information</h4><p class="ins-none">The lecturer didn’t mention exams, tests or quizzes.</p></section>')
          + list('Worth reviewing', c.worth_reviewing, (x) => `<li><span>${esc(x.text)}${x.reason ? ` <span class="ins-sub">— ${esc(x.reason)}</span>` : ''}</span>${chips(x.refs)}</li>`, 'Not tied to an exam in the recording.');
      case 'meeting_recap':
        return `${c.overview ? `<p class="tool-lead">${esc(c.overview)}</p>` : ''}
          ${c.participants?.length ? `<section class="tool-sec"><h4>Participants</h4><div class="lib-folders">${c.participants.map((x) => `<span class="lib-folder">${esc(x.label)}</span>`).join('')}</div></section>` : ''}
          ${topics('Topics discussed', c.topics)}
          ${list('Confirmed decisions', c.decisions, (x) => `<li><span>${esc(x.text)}</span>${ev(x.evidence)}${chips(x.refs)}</li>`) || '<section class="tool-sec"><h4>Confirmed decisions</h4><p class="ins-none">No decision was explicitly agreed.</p></section>'}
          ${c.action_items?.length ? `<section class="tool-sec"><h4>Action items</h4><ul class="ins-list">${c.action_items.map(action).join('')}</ul></section>` : ''}
          ${list('Open questions', c.open_questions, (x) => `<li><span>${esc(x.text)}</span>${chips(x.refs)}</li>`)}
          ${list('Follow-ups', c.follow_ups, (x) => `<li><span>${esc(x.text)}</span>${chips(x.refs)}</li>`)}
          ${list('Important dates', c.important_dates, (x) => `<li><span><b>${esc(x.when)}</b> — ${esc(x.what)}</span>${chips(x.refs)}</li>`)}`;
      case 'action_plan':
        return c.tasks?.length ? groupByOwner(c.tasks).map(([owner, tasks]) => `<section class="tool-sec"><h4>${esc(owner)} <span class="ins-sub">· ${tasks.length}</span></h4><ul class="ins-list">${tasks.map(action).join('')}</ul></section>`).join('')
          : '<p class="ins-none">No tasks were stated in this recording.</p>';
      case 'followup_email':
        return `<div class="draft"><div class="draft-subject"><span class="ins-label">Subject</span> ${esc(c.subject)}</div><div class="draft-body">${esc(c.body)}</div></div>
          ${c.unverified?.length ? `<div class="ins-msg warn"><span>Check before sending — not found in the recording: ${c.unverified.map((d) => `<b>${esc(d)}</b>`).join(', ')}</span></div>` : ''}
          ${c.facts?.length ? `<details class="draft-facts"><summary>Based on ${c.facts.length} things said in the meeting</summary><ul class="ins-points">${c.facts.map((f) => `<li><span>${esc(f.fact)}</span>${chips(f.refs)}</li>`).join('')}</ul></details>` : ''}`;
      case 'reply_draft':
        return `<div class="draft"><div class="draft-body">${esc(c.reply)}</div></div>
          ${c.unverified?.length ? `<div class="ins-msg warn"><span>Check before sending — not in the message: ${c.unverified.map((d) => `<b>${esc(d)}</b>`).join(', ')}</span></div>` : ''}
          ${c.addresses?.length ? `<details class="draft-facts"><summary>Replies to</summary><ul class="ins-points">${c.addresses.map((f) => `<li><span>${esc(f.request)}</span>${chips(f.refs)}</li>`).join('')}</ul></details>` : ''}`;
      case 'interview_qa':
        return `${c.is_interview === false ? '<p class="ins-sub">This recording isn’t mainly a question-and-answer exchange, so only the genuine questions are listed.</p>' : ''}
          ${c.pairs?.length ? `<ol class="qa-list">${c.pairs.map((x) => `<li class="ins-item qa"><div class="qa-q"><span class="qa-who">${esc(x.asked_by || 'Question')}</span>${esc(x.question)}${at(x.refs?.[0])}</div><div class="qa-a"><span class="qa-who">${esc(x.answered_by || 'Answer')}</span>${esc(x.response)}</div></li>`).join('')}</ol>` : '<p class="ins-none">No question-and-answer exchanges found.</p>'}
          ${quotes(c.quotes)}`;
      case 'episode_notes':
        return `${c.summary ? `<p class="tool-lead">${esc(c.summary)}</p>` : ''}${topics('Chapter outline', c.outline)}
          ${list('Key takeaways', c.takeaways, (x) => `<li><span>${esc(x.text)}</span>${chips(x.refs)}</li>`)}${quotes(c.quotes)}`;
      case 'flashcards': return deckHtml(a, byId);
      default: return '';
    }
  }

  // ---------- flashcards ----------
  function deckState(a) {
    const k = `${a.id}:${a.updatedAt}`;
    if (!ui.deck.has(k)) ui.deck.set(k, { i: 0, flipped: false, order: a.content.cards.map((_, i) => i) });
    return ui.deck.get(k);
  }
  function deckHtml(a, byId) {
    const cards = a.content.cards || [];
    if (!cards.length) return '<p class="ins-none">There wasn’t enough distinct material for flashcards.</p>';
    const d = deckState(a);
    const card = cards[d.order[d.i]];
    const src = card.refs?.[0] != null ? byId.get(card.refs[0]) : null;
    return `<div class="deck" data-deck="${a.id}">
      <div class="deck-count mono">${d.i + 1} / ${cards.length}</div>
      <button type="button" class="fc ${d.flipped ? 'flipped' : ''}" data-act="flip" aria-label="${d.flipped ? 'Answer shown. Activate to show the question' : 'Question shown. Activate to show the answer'}">
        <span class="fc-side">${d.flipped ? 'Answer' : 'Question'}</span>
        <span class="fc-text">${esc(d.flipped ? card.back : card.front)}</span>
        <span class="fc-hint">${d.flipped ? 'Tap to see the question' : 'Tap to reveal the answer'}</span>
      </button>
      <div class="fc-src">${d.flipped && src ? `Said at ${api.chips(card.refs, byId)}` : '&nbsp;'}</div>
      <div class="deck-nav">
        <button class="btn btn-ghost" type="button" data-act="prev" ${d.i === 0 ? 'disabled' : ''} aria-label="Previous card">← Prev</button>
        <button class="btn btn-ghost" type="button" data-act="flip">${d.flipped ? 'Question' : 'Answer'}</button>
        <button class="btn btn-ghost" type="button" data-act="next" ${d.i === cards.length - 1 ? 'disabled' : ''} aria-label="Next card">Next →</button>
      </div>
      <div class="deck-tools"><button class="btn btn-ghost btn-sm" type="button" data-act="shuffle">Shuffle</button><button class="btn btn-ghost btn-sm" type="button" data-act="restart">Restart</button></div>
    </div>`;
  }

  // ---------- Practice Quiz ----------
  // setup → one question at a time → instant feedback with the proof from the recording → result.
  // The questions are the stored, grounded quiz; quiz-engine.js only orders, shuffles and scores them.
  function quizView(a) {
    const k = `${a.id}:${a.updatedAt}`;
    if (!ui.quiz.has(k)) ui.quiz.set(k, { phase: 'setup', run: null });
    return ui.quiz.get(k);
  }
  const crumb = () => `<nav class="study-crumb" aria-label="Breadcrumb"><button type="button" data-act="tools">Create</button><span aria-hidden="true">›</span><span aria-current="page">Practice Quiz</span></nav>`;

  // QUESTION → ANSWER → PROOF: hear the moment (when the audio is open) or read the exact line
  function proofHtml(q, byId) {
    const s = q.refs?.length ? byId.get(q.refs[0]) : null;
    if (!s) return '';
    const t = fmtClock(s.start);
    const play = api.canPlay?.();
    return `<div class="proof">
      ${play ? `<button class="hear" type="button" data-seek="${s.start}" data-ref="${s.id}">${ICON.headphones}<span>Hear it at ${t}</span></button>` : ''}
      <details class="proof-line"><summary>${play ? `${ICON.quote}<span>Show the line</span>` : `${ICON.quote}<span>See it at ${t}</span>`}</summary>
        <blockquote><span class="proof-meta"><span class="mono">${t}</span>${s.speaker ? ` · ${esc(s.speaker)}` : ''}</span><span class="proof-text">${esc(s.text)}</span>${play ? '' : `<button class="fb-link" type="button" data-seek="${s.start}" data-ref="${s.id}">Open in transcript</button>`}</blockquote>
      </details>
    </div>`;
  }

  function quizSetupHtml({ sel, a, busy, err, stale }) {
    const spec = TOOL_SETTINGS.quiz;
    const minutes = (api.duration?.() || 0) / 60;
    const label = (name, v) => (name === 'size' ? String(quizQuestionCount(minutes, v)) : spec[name].options[v]);
    const ctl = (name) => `<div class="setup-ctl"><span class="setup-label" id="ql-${name}">${esc(spec[name].label)}</span>
      <div class="pick" role="radiogroup" aria-labelledby="ql-${name}">${Object.keys(spec[name].options).map((v) => `<button type="button" role="radio" aria-checked="${sel[name] === v}" tabindex="${sel[name] === v ? 0 : -1}" class="${sel[name] === v ? 'on' : ''}" data-set="${name}" data-val="${v}">${esc(label(name, v))}</button>`).join('')}</div></div>`;
    const n = a?.content?.questions?.length || 0;
    const empty = a?.content && !n;
    const last = a?.progress?.last_score != null ? ` · Last score ${a.progress.last_score}/${a.progress.total}` : '';
    return `<div class="study study-setup">
      ${crumb()}
      <section class="study-card setup-card" aria-labelledby="quizTitle">
        <span class="study-badge" aria-hidden="true">${ICON.quiz}</span>
        <h3 class="study-title" id="quizTitle">Practice Quiz</h3>
        <p class="study-sub">Test yourself on this recording.</p>
        <div class="setup-grid">${ctl('size')}${ctl('difficulty')}${ctl('types')}</div>
        ${stale && !busy ? '<div class="ins-msg warn"><span>The transcript changed after these questions were written.</span><button class="btn btn-ghost btn-sm" type="button" data-act="regen">Update</button></div>' : ''}
        ${err && !busy ? api.errorBox(err, 'regen', n ? "New questions couldn't be written; your current quiz still works." : "The quiz couldn't be created.") : ''}
        ${busy ? api.loading(TOOL_INFO.quiz.loading) : `<button class="btn btn-primary study-start" type="button" data-act="start"${empty ? ' disabled' : ''}>Start Quiz <span aria-hidden="true">→</span></button>`}
        <p class="setup-meta">${empty ? 'The recording didn’t support good questions with these settings.' : n ? `${n} question${n === 1 ? '' : 's'} ready${last} · retakes are free` : 'Questions are written from this recording once; retakes are free.'}</p>
        ${!n && !busy ? api.privacyLine : ''}
      </section>
      ${a?.content ? `<div class="study-tools">
        <button class="btn btn-ghost btn-sm" type="button" data-act="copy">Copy</button>
        <button class="btn btn-ghost btn-sm" type="button" data-act="export">Export…</button>
        ${!stale && !busy ? '<button class="btn btn-ghost btn-sm" type="button" data-act="regen-confirm">New questions</button>' : ''}
        <button class="btn btn-ghost btn-sm tool-del" type="button" data-act="delete">Delete quiz</button></div>` : ''}
    </div>`;
  }

  function quizPlayHtml(a, v, byId) {
    const qs = a.content.questions, run = v.run, it = currentItem(run), q = qs[it.qi], ans = run.answers[run.i];
    const total = run.items.length, done = answeredCount(run), right = correctCount(run);
    const kindLabel = { multiple_choice: 'Multiple choice', true_false: 'True or false', short_answer: 'Short answer' }[q.type] || '';
    let answers;
    if (q.type === 'short_answer') {
      answers = ans
        ? `<div class="sa-given ${ans.correct ? 'right' : 'wrong'}"><span class="sa-label">Your answer</span><b>${esc(ans.given)}</b><span class="ans-mark" aria-hidden="true">${ans.correct ? ICON.check : ICON.x}</span></div>`
        : `<form class="sa" data-act="sa" novalidate><label class="sr-only" for="saInput">Your answer</label><input id="saInput" class="sa-input" type="text" maxlength="200" placeholder="Type your answer" autocomplete="off" enterkeyhint="done" /><button class="btn btn-primary" type="submit">Check</button></form>`;
    } else {
      const tf = q.type === 'true_false';
      answers = `<div class="answers${tf ? ' tf' : ''}" role="group" aria-labelledby="qText">${it.order.map((j, pos) => {
        const o = q.options[j];
        const isRight = o === q.answer, picked = ans?.given === o;
        const state = ans ? (isRight ? 'right' : picked ? 'wrong' : 'dim') : '';
        const key = tf ? o : String.fromCharCode(65 + pos);
        const sr = ans ? (isRight ? ', correct answer' : picked ? ', your answer, not correct' : '') : '';
        return `<button type="button" class="ans ${state}" data-opt="${j}"${ans ? ' aria-disabled="true"' : ''} aria-label="${esc(`${tf ? '' : `${key}. `}${o}${sr}`)}">
          <span class="ans-key" aria-hidden="true">${tf ? (o === 'True' ? ICON.check : ICON.x) : key}</span><span class="ans-text">${esc(o)}</span><span class="ans-mark" aria-hidden="true">${state === 'right' ? ICON.check : state === 'wrong' ? ICON.x : ''}</span></button>`;
      }).join('')}</div>`;
    }
    const fb = ans ? `<div class="fb ${ans.correct ? 'right' : 'wrong'}" role="status">
        <p class="fb-head"><span class="fb-ic" aria-hidden="true">${ans.correct ? ICON.check : ICON.x}</span>${ans.correct ? 'Correct' : 'Not quite'}</p>
        ${!ans.correct ? `<p class="fb-answer"><span>Correct answer</span><b>${esc(q.answer)}</b></p>` : ''}
        ${q.explanation ? `<p class="fb-why">${esc(q.explanation)}</p>` : ''}
        ${proofHtml(q, byId)}
        ${q.type === 'short_answer' && !ans.correct && ans.given ? '<button class="fb-link" type="button" data-act="mark-right">My answer was right</button>' : ''}
      </div>` : '';
    return `<div class="study quiz${ans ? (ans.correct ? ' is-right' : ' is-wrong') : ''}" data-quiz="${a.id}">
      <header class="study-top">
        <div class="study-top-row">${crumb()}<button class="study-exit" type="button" data-act="exit">${ICON.close}<span>End quiz</span></button></div>
        <div class="study-prog"><span class="study-count">Question ${run.i + 1} of ${total}</span>${done ? `<span class="study-score">${ICON.check}${right} correct</span>` : ''}</div>
        <div class="study-bar" role="progressbar" aria-label="Quiz progress" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${done}"><span style="width:${(done / total) * 100}%"></span></div>
      </header>
      <section class="study-card q-card">
        <p class="q-kind">${esc(kindLabel)}${run.kind === 'missed' ? ' · from your missed questions' : ''}</p>
        <h3 class="q-text" id="qText" tabindex="-1">${esc(q.question)}</h3>
        ${answers}
        ${fb}
      </section>
      ${ans ? `<div class="study-next"><button class="btn btn-primary study-continue" type="button" data-act="qnext">${run.i === total - 1 ? 'See results' : 'Continue'} <span aria-hidden="true">→</span></button></div>` : ''}
    </div>`;
  }

  function quizResultHtml(a, v) {
    const qs = a.content.questions, r = summary(v.run);
    const pct = Math.round((r.score / r.total) * 100), perfect = r.score === r.total;
    const msg = perfect ? 'Every answer right. Nicely done.' : pct >= 80 ? 'Great work — just a little to review.' : pct >= 50 ? 'Good progress — a few to review.' : 'Keep going — you’re getting there.';
    const C = 2 * Math.PI * 52;
    const sparks = perfect ? `<div class="res-sparks" aria-hidden="true">${Array.from({ length: 12 }, (_, i) => `<i style="--a:${i * 30}deg;--d:${(i % 4) * 50}ms"></i>`).join('')}</div>` : '';
    return `<div class="study study-result${perfect ? ' perfect' : ''}">
      ${crumb()}
      <section class="study-card result-card" aria-labelledby="resTitle">
        ${sparks}
        <p class="res-eyebrow">${v.run.kind === 'missed' ? 'Missed questions done' : 'Quiz complete'}</p>
        <div class="res-ring" role="img" aria-label="${r.score} of ${r.total} correct, ${pct} percent">
          <svg viewBox="0 0 120 120" aria-hidden="true"><defs><linearGradient id="resGrad" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#22d3ee"/><stop offset=".5" stop-color="#a78bfa"/><stop offset="1" stop-color="#f472b6"/></linearGradient></defs>
            <circle cx="60" cy="60" r="52" class="res-track"/><circle cx="60" cy="60" r="52" class="res-arc" style="stroke-dasharray:${C.toFixed(1)};--off:${(C * (1 - r.score / r.total)).toFixed(1)}"/></svg>
          <div class="res-num"><b>${r.score} / ${r.total}</b><span>${pct}%</span></div>
        </div>
        <h3 class="res-title" id="resTitle" tabindex="-1">${perfect ? 'Perfect score' : msg}</h3>
        ${perfect ? `<p class="res-msg">${msg}</p>` : ''}
        <div class="res-split">
          <div class="res-chip strong">${ICON.check}<b>${r.strong.length}</b><span>Strong</span></div>
          <div class="res-chip review">${ICON.loop}<b>${r.missed.length}</b><span>To review</span></div>
        </div>
        <div class="res-actions">
          ${r.missed.length ? '<button class="btn btn-primary" type="button" data-act="review">Review missed questions</button><button class="btn btn-ghost" type="button" data-act="retake-missed">Retake missed questions</button>' : ''}
          <button class="btn ${r.missed.length ? 'btn-ghost' : 'btn-primary'}" type="button" data-act="retake">Retake full quiz</button>
        </div>
        <button class="study-back" type="button" data-act="tools">← Back to Create</button>
      </section>
      ${r.missed.length ? `<section class="miss-list" aria-label="Questions to review"><h4 class="miss-head">To review</h4>${r.missed.map((qi) => `<article class="miss-card"><p class="miss-q">${esc(qs[qi].question)}</p><p class="miss-a">${ICON.check}<span>${esc(qs[qi].answer)}</span></p></article>`).join('')}</section>` : ''}
    </div>`;
  }

  function quizReviewHtml(a, v, byId) {
    const qs = a.content.questions, r = summary(v.run);
    const given = new Map(v.run.items.map((it, k) => [it.qi, v.run.answers[k]?.given]));
    return `<div class="study study-review">
      <div class="study-top-row">${crumb()}<button class="study-exit" type="button" data-act="results">← Results</button></div>
      <h3 class="study-title" id="revTitle" tabindex="-1">Review missed questions</h3>
      ${r.missed.map((qi, n) => {
        const q = qs[qi];
        return `<section class="study-card rev-card" aria-label="Missed question ${n + 1}">
          <p class="q-kind">Question ${n + 1} of ${r.missed.length}</p>
          <p class="rev-q">${esc(q.question)}</p>
          ${given.get(qi) ? `<p class="rev-given">${ICON.x}<span>You answered <b>${esc(given.get(qi))}</b></span></p>` : ''}
          <p class="fb-answer"><span>Correct answer</span><b>${esc(q.answer)}</b></p>
          ${q.explanation ? `<p class="fb-why">${esc(q.explanation)}</p>` : ''}
          ${proofHtml(q, byId)}
        </section>`;
      }).join('')}
      <div class="res-actions"><button class="btn btn-primary" type="button" data-act="retake-missed">Retake missed questions</button><button class="btn btn-ghost" type="button" data-act="retake">Retake full quiz</button></div>
    </div>`;
  }

  function renderQuiz() {
    const kind = 'quiz';
    const sel = selOf(kind);
    const { key, a } = current(kind);
    const busy = api.busy(kind, key) || a?.status === 'generating';
    const err = api.error(kind, key) || (a?.status === 'failed' ? { message: a.error } : null);
    const stale = a?.content && api.contentVersion() != null && a.sourceVersion < api.contentVersion();
    // "Start Quiz" asked for questions that had to be written first: begin as soon as they're here
    if (ui.autoStart === key && a?.content?.questions?.length && quizView(a).phase === 'setup') { ui.autoStart = null; startRun(a, newRun(a.content.questions)); }
    const v = a?.content?.questions?.length ? quizView(a) : null;
    const byId = api.segById();
    if (v?.phase === 'play') return quizPlayHtml(a, v, byId);
    if (v?.phase === 'result') return quizResultHtml(a, v);
    if (v?.phase === 'review') return quizReviewHtml(a, v, byId);
    return quizSetupHtml({ sel, a, busy, err, stale });
  }
  function startRun(a, run) {
    const v = quizView(a);
    v.run = run; v.phase = 'play';
    ui.focus = 'question';
    mascotSignal('quiz-start');
  }
  // reopening a quiz that is still in progress: the mascot goes back to focus mode
  function resumeSignal(a) { if (a?.content?.questions?.length && quizView(a).phase === 'play') mascotSignal('quiz-start'); }

  // ---------- events ----------
  function bind(p) {
    p.querySelectorAll('[data-goto]').forEach((b) => b.addEventListener('click', () => api.showTab(b.dataset.goto)));
    p.querySelectorAll('[data-tool]').forEach((b) => b.addEventListener('click', () => {
      if (b.dataset.tool === 'export') return api.openExport();
      ui.tool = b.dataset.tool;
      delete ui.sel[ui.tool]; // start from the latest result's settings
      if (ui.tool === 'quiz') resumeSignal(current('quiz').a);
      // a reply / email with nothing created yet: ask what it should do straight away
      if (SETUP_DIALOG.has(ui.tool) && !latest(ui.tool)) { api.refresh(); openSetup(ui.tool); return; }
      api.refresh();
      p.scrollIntoView({ block: 'start', behavior: 'smooth' });
    }));
    const kind = ui.tool;
    if (!kind) return;
    p.querySelectorAll('[data-set]').forEach((b) => b.addEventListener('click', () => { selOf(kind)[b.dataset.set] = b.dataset.val; api.refresh(); }));
    p.querySelectorAll('[data-act="setup"]').forEach((b) => b.addEventListener('click', () => openSetup(kind)));
    const info = TOOL_INFO[kind];
    const settings = { ...selOf(kind) };
    const { key, a } = current(kind);
    p.querySelector('[data-act="tools"]')?.addEventListener('click', () => { ui.tool = null; api.refresh(); });
    p.querySelector('[data-act="create"]')?.addEventListener('click', () => api.generate(kind, settings, false));
    p.querySelectorAll('[data-act="regen"]').forEach((b) => b.addEventListener('click', () => api.generate(kind, settings, true)));
    p.querySelector('[data-act="regen-confirm"]')?.addEventListener('click', async () => {
      if (await api.confirm(`Regenerate ${info.label}?`, 'This replaces the current version with a newly generated one.', 'Regenerate')) api.generate(kind, settings, true);
    });
    p.querySelector('[data-act="copy"]')?.addEventListener('click', () => api.copy(blocksToText(artifactBlocks(kind, a.content, api.timeOf)), info.label));
    p.querySelector('[data-act="export"]')?.addEventListener('click', () => api.openExport(`tool:${kind}:${key}`));    p.querySelector('[data-act="delete"]')?.addEventListener('click', async () => {
      if (await api.confirm(`Delete ${info.label}?`, 'Only this created item is removed. The recording, its transcript and everything else stay.', 'Delete', true)) api.remove(a);
    });

    // flashcards
    const deck = p.querySelector('.deck');
    if (deck && a) {
      const d = deckState(a);
      const n = a.content.cards.length;
      const go = (fn) => { fn(); api.refresh(); requestAnimationFrame(() => api.panel().querySelector('.fc')?.focus()); };
      deck.addEventListener('click', (e) => {
        const act = e.target.closest('[data-act]')?.dataset.act;
        if (act === 'flip') { mascotSignal('flashcard-flip'); go(() => { d.flipped = !d.flipped; }); }
        else if (act === 'next' && d.i < n - 1) go(() => { d.i++; d.flipped = false; });
        else if (act === 'prev' && d.i > 0) go(() => { d.i--; d.flipped = false; });
        else if (act === 'shuffle') go(() => { d.order = d.order.map((x) => [Math.random(), x]).sort((x, y) => x[0] - y[0]).map((x) => x[1]); d.i = 0; d.flipped = false; });
        else if (act === 'restart') go(() => { d.order = a.content.cards.map((_, i) => i); d.i = 0; d.flipped = false; });
      });
      deck.addEventListener('keydown', (e) => {
        if (e.key === 'ArrowRight' && d.i < n - 1) { e.preventDefault(); go(() => { d.i++; d.flipped = false; }); }
        else if (e.key === 'ArrowLeft' && d.i > 0) { e.preventDefault(); go(() => { d.i--; d.flipped = false; }); }
      });
    }
  }

  // ---------- Practice Quiz: events ----------
  function bindQuiz(p) {
    const kind = 'quiz';
    const info = TOOL_INFO[kind];
    const settings = { ...selOf(kind) };
    const { key, a } = current(kind);
    const qs = a?.content?.questions || [];
    const v = qs.length ? quizView(a) : null;
    const rerender = (focus) => { ui.focus = focus; api.refresh(); };
    const on = (sel, fn) => p.querySelectorAll(sel).forEach((b) => b.addEventListener('click', fn));

    // back to Create: a finished quiz reopens on its setup (with the last score); one in progress resumes
    on('[data-act="tools"]', () => {
      if (v?.phase === 'play') mascotSignal('quiz-end');
      if (v && v.phase !== 'play') { v.phase = 'setup'; v.run = null; }
      ui.tool = null; api.refresh();
    });
    // setup choices: radio groups (click, or arrow keys inside the group)
    on('[data-set]', (e) => { const b = e.currentTarget; selOf(kind)[b.dataset.set] = b.dataset.val; rerender(`set:${b.dataset.set}`); });
    p.querySelectorAll('.pick').forEach((g) => g.addEventListener('keydown', (e) => {
      const opts = [...g.querySelectorAll('[role="radio"]')];
      const i = opts.indexOf(document.activeElement);
      const d = { ArrowRight: 1, ArrowDown: 1, ArrowLeft: -1, ArrowUp: -1 }[e.key];
      if (i < 0 || !d) return;
      e.preventDefault();
      const b = opts[(i + d + opts.length) % opts.length];
      selOf(kind)[b.dataset.set] = b.dataset.val;
      rerender(`set:${b.dataset.set}`);
    }));
    on('[data-act="start"]', () => {
      if (qs.length) { startRun(a, newRun(qs)); api.refresh(); p.scrollIntoView({ block: 'start', behavior: 'smooth' }); return; }
      ui.autoStart = key;
      api.generate(kind, settings, false);
    });
    on('[data-act="regen"]', () => api.generate(kind, settings, true));
    on('[data-act="regen-confirm"]', async () => {
      if (await api.confirm('Write new questions?', 'This replaces this quiz with newly generated questions from the recording.', 'Write new questions')) api.generate(kind, settings, true);
    });
    on('[data-act="copy"]', () => api.copy(blocksToText(artifactBlocks(kind, a.content, api.timeOf)), info.label));
    on('[data-act="export"]', () => api.openExport(`tool:${kind}:${key}`));
    on('[data-act="delete"]', async () => {
      if (await api.confirm(`Delete ${info.label}?`, 'Only this quiz is removed. The recording, its transcript and everything else stay.', 'Delete', true)) api.remove(a);
    });
    if (!v) return focusAfter(p);

    const run = v.run;
    on('[data-act="exit"]', () => { v.phase = 'setup'; v.run = null; mascotSignal('quiz-end'); rerender('setup'); });
    on('[data-act="results"]', () => { v.phase = 'result'; rerender('result'); });
    on('[data-act="review"]', () => { v.phase = 'review'; rerender('review'); });
    on('[data-act="retake"]', () => { startRun(a, newRun(qs, { shuffle: true })); api.refresh(); });
    on('[data-act="retake-missed"]', () => { startRun(a, newRun(qs, { only: summary(run).missed, shuffle: true })); api.refresh(); });

    if (v.phase === 'play') {
      const choose = (given) => {
        if (run.answers[run.i]) return;
        const ok = gradeAnswer(run, qs, given);
        mascotSignal(ok ? 'quiz-correct' : 'quiz-wrong');
        rerender('continue');
      };
      const next = () => {
        if (!run.answers[run.i]) return;
        if (!advance(run)) { mascotSignal('quiz-next'); rerender('question'); return; }
        v.phase = 'result';
        const r = summary(run);
        if (run.kind === 'full') {
          const prev = a.progress || {};
          api.saveProgress(a, { last_score: r.score, total: r.total, attempts: (prev.attempts || 0) + 1, completed_at: new Date().toISOString(), missed: r.missed });
        }
        mascotSignal('quiz-done', { score: r.score, total: r.total });
        rerender('result');
      };
      p.querySelectorAll('[data-opt]').forEach((b) => b.addEventListener('click', () => choose(qs[currentItem(run).qi].options[Number(b.dataset.opt)])));
      p.querySelector('[data-act="sa"]')?.addEventListener('submit', (e) => {
        e.preventDefault();
        const given = e.target.querySelector('input').value.trim();
        if (given) choose(given);
      });
      on('[data-act="mark-right"]', () => { overrideCorrect(run); rerender('continue'); });
      on('[data-act="qnext"]', next);
      // keys: A–D (or 1–4) pick a choice, T / F for true or false, Enter continues
      ui.quizKey = (e) => {
        if (e.target.closest('input, textarea, select, summary') || e.ctrlKey || e.metaKey || e.altKey) return;
        const q = qs[currentItem(run).qi];
        if (run.answers[run.i]) {
          if (e.key === 'Enter' && !e.target.closest('button')) { e.preventDefault(); next(); }
          return;
        }
        const k = e.key.toLowerCase();
        let j = -1;
        if (q.type === 'true_false') j = k === 't' ? q.options.indexOf('True') : k === 'f' ? q.options.indexOf('False') : -1;
        else if (q.type === 'multiple_choice') {
          const pos = /^[a-e]$/.test(k) ? k.charCodeAt(0) - 97 : /^[1-5]$/.test(k) ? Number(k) - 1 : -1;
          j = pos >= 0 ? currentItem(run).order[pos] ?? -1 : -1;
        }
        if (j >= 0) { e.preventDefault(); choose(q.options[j]); }
      };
    }
    focusAfter(p);
  }
  // after a re-render, put focus where the learner continues (and never steal it otherwise)
  function focusAfter(p) {
    const f = ui.focus; ui.focus = null;
    if (!f) return;
    const el = f === 'question' ? (p.querySelector('.sa-input') || p.querySelector('#qText'))
      : f === 'continue' ? p.querySelector('[data-act="qnext"]')
        : f === 'result' ? p.querySelector('#resTitle')
          : f === 'review' ? p.querySelector('#revTitle')
            : f === 'setup' ? p.querySelector('[data-act="start"]')
              : f.startsWith('set:') ? p.querySelector(`[data-set="${f.slice(4)}"][aria-checked="true"]`) : null;
    el?.focus({ preventScroll: f.startsWith('set:') || f === 'continue' });
    // the answer's feedback is the next thing to read: bring it (and the Continue button) into view
    if (f === 'continue') p.querySelector('.fb')?.scrollIntoView({ block: 'nearest', behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' });
  }

  return {
    render(panel) {
      if (!panel.dataset.quizKeys) {             // one keyboard handler per panel; each screen sets ui.quizKey
        panel.dataset.quizKeys = '1';
        panel.addEventListener('keydown', (e) => ui.quizKey?.(e));
      }
      ui.quizKey = null;
      if (ui.tool === 'quiz') { panel.innerHTML = renderQuiz(); bindQuiz(panel); return; }
      panel.innerHTML = ui.tool ? renderTool() : renderList();
      bind(panel);
    },
    reset() { ui.tool = null; },
  };
}
