-- Phase 4: My Library as a personal archive — favorites, folders, "recently opened", and search.
--
-- Design
--   * transcriptions.is_favorite     one owner per recording, so a flag is simpler than a table.
--   * transcriptions.last_opened_at  set when a recording is opened; drives the "Recent" view.
--   * transcriptions.search_tsv      full-text index of the title (weight A) and the transcript text
--                                     (weight C), generated by the database so it can never be stale or
--                                     forged. Timestamps and generic "Speaker N" labels are left out; real
--                                     speaker names stay in, so a search for a person finds what they said.
--   * folders / folder_items         user-made folders; a recording can be in several folders. Deleting a
--                                     folder deletes only its memberships, never the recordings.
--   * transcription_insights.search_tsv
--                                     the text of generated Notes (headings + notes only), kept by a trigger,
--                                     so Notes can be searched separately from (and ranked below) transcripts.
--   * search_library() / library_list() / library_stats()
--                                     SECURITY INVOKER functions: they run as the signed-in user, so Row
--                                     Level Security applies to every row they read, exactly like a direct
--                                     query. They also filter on auth.uid() so the per-user indexes are used.
--
-- Nothing here changes transcript text, segments, content_version or any stored AI result.

create extension if not exists btree_gin with schema extensions;

-- ---------------------------------------------------------------------------
-- transcriptions: favorite, recently opened, search vector
-- ---------------------------------------------------------------------------
alter table public.transcriptions
  add column is_favorite boolean not null default false,
  add column last_opened_at timestamptz,
  add column search_tsv tsvector generated always as (
    setweight(to_tsvector('english'::regconfig, coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english'::regconfig, left(
      regexp_replace(
        regexp_replace(
          regexp_replace(transcript_text, '^[^\n]*\nLength:[^\n]*\n', ''),          -- file name / length header
          '\[\d{1,2}(:\d{2}){1,2}\] Speaker \d+:', ' ', 'g'),                        -- "[0:14] Speaker 1:"
        '\[\d{1,2}(:\d{2}){1,2}\]', ' ', 'g'),                                       -- remaining "[0:14]"
      2000000)), 'C')
  ) stored;

-- search: one index per (user, word) so a search only touches the searching user's rows
create index transcriptions_search_idx on public.transcriptions using gin (user_id, search_tsv);
create index transcriptions_user_favorite_idx on public.transcriptions (user_id, created_at desc) where is_favorite;

grant update (is_favorite, last_opened_at) on public.transcriptions to authenticated;

-- ---------------------------------------------------------------------------
-- folders
-- ---------------------------------------------------------------------------
create table public.folders (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name       text not null check (char_length(btrim(name)) between 1 and 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- no two folders with the same name (ignoring case) for one user; also serves as the user_id index
create unique index folders_user_name_idx on public.folders (user_id, lower(btrim(name)));

create trigger folders_set_updated_at
  before update on public.folders
  for each row execute function public.set_updated_at();

create table public.folder_items (
  folder_id        uuid not null references public.folders (id) on delete cascade,
  transcription_id uuid not null references public.transcriptions (id) on delete cascade,
  user_id          uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at       timestamptz not null default now(),
  primary key (folder_id, transcription_id)
);

create index folder_items_transcription_idx on public.folder_items (transcription_id);
create index folder_items_user_id_idx on public.folder_items (user_id);

revoke all on public.folders, public.folder_items from anon, authenticated;
grant select, delete on public.folders to authenticated;
grant insert (name) on public.folders to authenticated;
grant update (name) on public.folders to authenticated;
grant select, delete on public.folder_items to authenticated;
grant insert (folder_id, transcription_id) on public.folder_items to authenticated;

alter table public.folders      enable row level security;
alter table public.folder_items enable row level security;

create policy "folders: read own"
  on public.folders for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "folders: insert own"
  on public.folders for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "folders: update own"
  on public.folders for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "folders: delete own"
  on public.folders for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "folder_items: read own"
  on public.folder_items for select to authenticated
  using ((select auth.uid()) = user_id);

-- both the folder and the recording must belong to the user adding the membership
create policy "folder_items: insert own"
  on public.folder_items for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (select 1 from public.folders f where f.id = folder_id and f.user_id = (select auth.uid()))
    and exists (select 1 from public.transcriptions t where t.id = transcription_id and t.user_id = (select auth.uid()))
  );

create policy "folder_items: delete own"
  on public.folder_items for delete to authenticated
  using ((select auth.uid()) = user_id);

-- ---------------------------------------------------------------------------
-- Notes search vector (generated Notes only; kept by a trigger)
-- ---------------------------------------------------------------------------
alter table public.transcription_insights add column search_tsv tsvector;

create or replace function public.set_notes_search()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.kind = 'notes' and new.status = 'ready' and new.content is not null then
    new.search_tsv := to_tsvector('english'::regconfig, concat_ws(' ',
      (select string_agg(x #>> '{}', ' ') from jsonb_path_query(new.content, '$.sections[*].heading') as x),
      (select string_agg(x #>> '{}', ' ') from jsonb_path_query(new.content, '$.sections[*].items[*].text') as x)));
  else
    new.search_tsv := null;
  end if;
  return new;
end;
$$;

create trigger transcription_insights_notes_search
  before insert or update of kind, status, content on public.transcription_insights
  for each row execute function public.set_notes_search();

revoke execute on function public.set_notes_search() from public, anon, authenticated;

-- existing Notes (written before this migration): fill the vector without touching the Notes themselves
update public.transcription_insights
   set search_tsv = to_tsvector('english'::regconfig, concat_ws(' ',
     (select string_agg(x #>> '{}', ' ') from jsonb_path_query(content, '$.sections[*].heading') as x),
     (select string_agg(x #>> '{}', ' ') from jsonb_path_query(content, '$.sections[*].items[*].text') as x)))
 where kind = 'notes' and status = 'ready' and content is not null;

create index transcription_insights_notes_search_idx
  on public.transcription_insights using gin (user_id, search_tsv) where kind = 'notes';

-- ---------------------------------------------------------------------------
-- helpers
-- ---------------------------------------------------------------------------
-- "1:02:03" / "4:05" -> seconds (for transcripts saved before line-level timestamps)
create or replace function public.clock_to_seconds(c text)
returns double precision
language sql
immutable
set search_path = ''
as $$
  select coalesce(sum(u.p::double precision * power(60, u.n - u.i)), 0)
  from (select a.p, a.i, count(*) over () as n from unnest(string_to_array(c, ':')) with ordinality as a(p, i)) u
$$;

-- ---------------------------------------------------------------------------
-- search_library: recordings matching a query, best first, each with its matching lines + timestamps.
--   Ranking: a title match outranks any transcript match; transcript relevance (ts_rank_cd) next; generated
--   Notes add only a small boost and are returned as separate hits marked source = 'notes'.
--   Query syntax: plain words (all must appear, English stemming: "pricing" finds "price"), "quoted
--   phrases", or, -excluded.
--   Line hits are computed only for the page of recordings returned. Older recordings without line-level
--   timestamps return paragraph hits (coarse = true) with the paragraph's own start time.
-- ---------------------------------------------------------------------------
create or replace function public.search_library(p_query text, p_limit integer default 10, p_offset integer default 0)
returns table (
  transcription_id uuid, title text, recording_type text, created_at timestamptz, duration_seconds integer,
  is_favorite boolean, title_match boolean, coarse boolean, score real, match_count integer, hits jsonb
)
language sql
stable
security invoker
set search_path = ''
as $$
with params as (
  select (select auth.uid()) as uid,
         websearch_to_tsquery('english'::regconfig, left(btrim(coalesce(p_query, '')), 200)) as q,
         '%' || replace(replace(replace(left(btrim(coalesce(p_query, '')), 200), '\', '\\'), '%', '\%'), '_', '\_') || '%' as pat,
         char_length(btrim(coalesce(p_query, ''))) >= 2 as ok
),
by_content as (
  select t.id from public.transcriptions t, params p
  where p.ok and numnode(p.q) > 0 and t.user_id = p.uid and t.search_tsv @@ p.q
),
by_title as (
  select t.id from public.transcriptions t, params p
  where p.ok and t.user_id = p.uid and t.title ilike p.pat
),
by_notes as (
  select i.transcription_id as id, max(ts_rank_cd(i.search_tsv, p.q)) as r
  from public.transcription_insights i, params p
  where p.ok and numnode(p.q) > 0 and i.user_id = p.uid and i.kind = 'notes' and i.search_tsv @@ p.q
  group by i.transcription_id
),
cand as (
  select t.id, t.title, t.recording_type, t.created_at, t.duration_seconds, t.is_favorite, t.segments, t.transcript_text,
         (t.title ilike p.pat) as title_match,
         ((case when numnode(p.q) > 0 and t.search_tsv @@ p.q then ts_rank_cd('{0.02,0.2,0.4,1.0}'::float4[], t.search_tsv, p.q, 1) else 0 end)
          + (case when t.title ilike p.pat then 10 else 0 end)
          + coalesce(0.1 * n.r, 0))::real as score
  from public.transcriptions t
  cross join params p
  left join by_notes n on n.id = t.id
  where t.user_id = p.uid
    and t.id in (select id from by_content union select id from by_title union select id from by_notes)
  order by score desc, t.created_at desc
  limit least(greatest(coalesce(p_limit, 10), 1), 50)
  offset greatest(coalesce(p_offset, 0), 0)
)
select c.id, c.title, c.recording_type, c.created_at, c.duration_seconds, c.is_favorite, c.title_match,
       not seg.has_segments, c.score, coalesce(th.cnt, 0)::integer,
       coalesce(th.hits, '[]'::jsonb) || coalesce(nh.hits, '[]'::jsonb)
from cand c
cross join params p
cross join lateral (
  select jsonb_typeof(c.segments) = 'array' and jsonb_array_length(c.segments) > 0 as has_segments
) seg
-- transcript lines (or paragraphs) that match
cross join lateral (
  select count(*) as cnt,
         jsonb_agg(jsonb_build_object(
           'source', 'transcript', 'line', z.line, 'start', z.start, 'speaker', z.speaker,
           'snippet', ts_headline('english'::regconfig, z.text, p.q,
             format('StartSel=%s, StopSel=%s, MaxWords=30, MinWords=12, ShortWord=2, MaxFragments=1', chr(2), chr(3))))
           order by z.line) filter (where z.rn <= 3) as hits
  from (
    select l.*, row_number() over (order by l.line) as rn
    from (
      select (x.o - 1)::integer as line, (x.e ->> 's')::double precision as start, x.e ->> 'sp' as speaker, x.e ->> 't' as text
      from jsonb_array_elements(case when seg.has_segments then c.segments else '[]'::jsonb end) with ordinality as x(e, o)
      union all
      select (x.o - 1)::integer, public.clock_to_seconds(x.m[1]), x.m[2], regexp_replace(x.m[3], '\s*\n\s*', ' ', 'g')
      from regexp_matches(case when seg.has_segments then '' else c.transcript_text end,
                          '\[(\d{1,2}(?::\d{2}){1,2})\] ([^\n]+):\n([^\n]+(?:\n[^\n]+)*)', 'g') with ordinality as x(m, o)
    ) l
    where numnode(p.q) > 0
      and to_tsvector('english'::regconfig,
            (case when l.speaker ~ '^Speaker \d+$' then '' else coalesce(l.speaker, '') end) || ' ' || coalesce(l.text, '')) @@ p.q
  ) z
) th
-- generated Notes that match (labelled as Notes, never mixed into transcript hits)
cross join lateral (
  select jsonb_agg(jsonb_build_object('source', 'notes', 'line', w.ref, 'start', w.start, 'speaker', null,
           'snippet', ts_headline('english'::regconfig, w.text, p.q,
             format('StartSel=%s, StopSel=%s, MaxWords=30, MinWords=12, ShortWord=2, MaxFragments=1', chr(2), chr(3))))
           order by w.ord) as hits
  from (
    select it.item ->> 'text' as text,
           (it.item -> 'refs' ->> 0)::integer as ref,
           case when seg.has_segments then (c.segments -> ((it.item -> 'refs' ->> 0)::integer) ->> 's')::double precision end as start,
           row_number() over (order by i.updated_at desc, s.so, it.io) as ord
    from public.transcription_insights i
    cross join lateral jsonb_array_elements(i.content -> 'sections') with ordinality as s(sec, so)
    cross join lateral jsonb_array_elements(s.sec -> 'items') with ordinality as it(item, io)
    where i.transcription_id = c.id and i.user_id = p.uid and i.kind = 'notes' and i.status = 'ready'
      and numnode(p.q) > 0 and to_tsvector('english'::regconfig, coalesce(it.item ->> 'text', '')) @@ p.q
  ) w
  where w.ord <= 2
) nh
order by c.score desc, c.created_at desc
$$;

-- ---------------------------------------------------------------------------
-- library_list: one page of the Library with filters and sorting, plus the total for those filters.
--   p_view: 'all' | 'favorites' | 'recent'   p_type: recording type or null ('general' includes unset)
--   p_sort: 'newest' | 'oldest' | 'longest' | 'shortest' | 'az' | 'recent'
-- ---------------------------------------------------------------------------
create or replace function public.library_list(
  p_view text default 'all', p_type text default null, p_folder uuid default null, p_since timestamptz default null,
  p_sort text default 'newest', p_limit integer default 24, p_offset integer default 0
)
returns table (
  id uuid, title text, recording_type text, created_at timestamptz, duration_seconds integer, is_favorite boolean,
  last_opened_at timestamptz, status text, speaker_count integer, coarse boolean, summary text, preview text,
  folder_ids uuid[], total bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
with page as (
  select t.id, t.title, t.recording_type, t.created_at, t.duration_seconds, t.is_favorite, t.last_opened_at, t.status,
         count(*) over () as total
  from public.transcriptions t
  where t.user_id = (select auth.uid())
    and (p_view is distinct from 'favorites' or t.is_favorite)
    and (p_type is null
         or (p_type = 'general' and coalesce(t.recording_type, 'general') = 'general')
         or t.recording_type = p_type)
    and (p_folder is null or exists (select 1 from public.folder_items fi where fi.folder_id = p_folder and fi.transcription_id = t.id))
    and (p_since is null or t.created_at >= p_since)
  order by
    case when p_sort = 'oldest' then t.created_at end asc,
    case when p_sort = 'longest' then t.duration_seconds end desc nulls last,
    case when p_sort = 'shortest' then t.duration_seconds end asc nulls last,
    case when p_sort = 'az' then lower(t.title) end asc,
    case when p_sort = 'recent' then coalesce(t.last_opened_at, t.created_at) end desc,
    t.created_at desc
  limit least(greatest(coalesce(p_limit, 24), 1), 100)
  offset greatest(coalesce(p_offset, 0), 0)
)
select pg.id, pg.title, pg.recording_type, pg.created_at, pg.duration_seconds, pg.is_favorite, pg.last_opened_at, pg.status,
       (case when seg.has_segments
             then (select count(distinct e ->> 'sp') from jsonb_array_elements(t.segments) e where e ->> 'sp' <> 'Unknown')
             else (select count(distinct m[1]) from regexp_matches(t.transcript_text, '^\[\d{1,2}(?::\d{2}){1,2}\] ([^\n]+):$', 'gn') m
                   where m[1] <> 'Unknown') end)::integer,
       not seg.has_segments,
       (select i.content ->> 'short_summary' from public.transcription_insights i
         where i.transcription_id = pg.id and i.kind = 'overview' and i.status = 'ready'
         order by i.updated_at desc limit 1),
       left(case when seg.has_segments then t.segments -> 0 ->> 't'
                 else substring(t.transcript_text from '\][^\n]*:\n([^\n]+)') end, 240),
       array(select fi.folder_id from public.folder_items fi where fi.transcription_id = pg.id),
       pg.total
from page pg
join public.transcriptions t on t.id = pg.id
cross join lateral (select jsonb_typeof(t.segments) = 'array' and jsonb_array_length(t.segments) > 0 as has_segments) seg
order by
  case when p_sort = 'oldest' then pg.created_at end asc,
  case when p_sort = 'longest' then pg.duration_seconds end desc nulls last,
  case when p_sort = 'shortest' then pg.duration_seconds end asc nulls last,
  case when p_sort = 'az' then lower(pg.title) end asc,
  case when p_sort = 'recent' then coalesce(pg.last_opened_at, pg.created_at) end desc,
  pg.created_at desc
$$;

-- ---------------------------------------------------------------------------
-- library_stats: the small overview in the Library header
-- ---------------------------------------------------------------------------
create or replace function public.library_stats(p_month_start timestamptz default null)
returns table (recordings bigint, seconds bigint, this_month bigint, favorites bigint, by_type jsonb)
language sql
stable
security invoker
set search_path = ''
as $$
  select count(*),
         coalesce(sum(t.duration_seconds), 0)::bigint,
         count(*) filter (where t.created_at >= coalesce(p_month_start, date_trunc('month', now()))),
         count(*) filter (where t.is_favorite),
         coalesce((select jsonb_object_agg(k.type, k.n) from (
                     select coalesce(x.recording_type, 'general') as type, count(*) as n
                     from public.transcriptions x where x.user_id = (select auth.uid()) group by 1) k), '{}'::jsonb)
  from public.transcriptions t
  where t.user_id = (select auth.uid())
$$;

revoke execute on function public.search_library(text, integer, integer) from public, anon;
revoke execute on function public.library_list(text, text, uuid, timestamptz, text, integer, integer) from public, anon;
revoke execute on function public.library_stats(timestamptz) from public, anon;
grant execute on function public.search_library(text, integer, integer) to authenticated;
grant execute on function public.library_list(text, text, uuid, timestamptz, text, integer, integer) to authenticated;
grant execute on function public.library_stats(timestamptz) to authenticated;
